### ISSUE TITLE
Add button for follow and unfollow

### ISSUE THREAD

**Issue by JohnYangSam** [SiliconValleyInsight/ios-template#4]
Add button for follow and unfollow

And a list of users to test and do so on

**Comment by vinogradnaya** [comment]
I'll add auto-followed users tomorrow, and for now to test follow/unfollow feature, please login with user: ivan, password: 111111. This user already follows / is being followed by several others.

**Comment by vinogradnaya** [comment]
I added autofollowed users, you may now try to unfollow / follow
